### PR TITLE
simple vendor links

### PR DESCRIPTION
**Pull request by xi**
This is meant as a simple replacement for #245. "Simple", because there is only a single link per manufacturer, so the UI is much simpler.

Regarding https://github.com/MPIB/Lagerregal/pull/245#issuecomment-433328450, I agree with @LizzAlice: `serialnumber` is the only relevant field at the moment.

A help text is currently still missing.

### CODE REVIEW

**Comment by octomike** [comment]
Devices may also have dynamic, devicetype-specific `typeattributevalue_set` attributes, which could contain useful meta information for the vendor links.

**Comment by octomike** [comment]
Multiple vendor links (think: driver packages, official device description, warranty status..) would be super nice, but not necessary for an early version of this feature.

**Comment by xi** [comment]
I added `name` and type attributes to the available fields. Since we don't know which type attributes are available I had to weaken the validation.

**Comment by xi** [comment]
As far as I understood this simplifies too much, so closing.

**Pull request closed without merging**
