### PR TITLE
Vendor links

### PR DESCRIPTION
**Pull request by LizzAlice**

### CODE REVIEW

**Comment by octomike** [comment]
will implement  #221

**Comment by octomike** [comment]
There are multiple problems with the manufacturer view when one adds 2 URLS.

2018-10-25-093912_679x200_scrot

It's not:

+ left aligned
+ using full width
+ breaks the devices table

**Comment by octomike** [comment]
Also, shouldn't adding a URL be part of the Edit dialogue? Are we not editing the manufacturer object?

**Comment by octomike** [comment]
I like the Help preview a lot. But please fix the example url to be be an actual url.
"Manuals" is not a TLD. (yet - I checked)

**Comment by octomike** [comment]
Unfortunately, hard coding the device serialnumber as the only template variable won't work. For starters I could think of adding all characterfields of the device model to be a viable option here.

The code uses pystache **and** django templates already. Why did you chose to implement your own template syntax here?

**Comment by octomike** [comment]
there is still some debug foo in there..

```
[25/Oct/2018 09:38:47] "POST /ajax/autocomplete_name HTTP/1.1" 200 0
RE!
<_sre.SRE_Match object; span=(80, 94), match='{serialnumber}'>
blubb!
serialnumber
[25/Oct/2018 09:38:49] "POST /manufacturers/1/urls/add HTTP/1.1" 302 0
```

**Comment by LizzAlice** [comment]
> Also, shouldn't adding a URL be part of the Edit dialogue? Are we not editing the manufacturer object?

We are giving the ManufacturerUrl object a foreign key to the Manufacturer object

**Comment by xi** [comment]
replaced #348

**Pull request closed without merging**
