### PR TITLE
python3 compatibility

### PR DESCRIPTION
**Pull request by xi**
see #195

I ran 2to3 and reviewed all changes manually. While I was at it I also fixed some pep8-related stylistic issues.

I was able to run all tests and start the testserver with python3.5. But everything should also still work with python2.7. I did not do in-depth with either version.

I understand that this is a rather big chunk. Feel free to cherry-pick individual commits or ask for changes.

### CODE REVIEW

**Comment by octomike** [comment]
Great stuff, but I'm afraid tests are far from complete :)

In a completely new environment I get an immediate error on "/":

```
(lagerregal_py3) [ladmin@lip-dev /opt/Lagerregal (feature-py3)] python manage.py runserver 0.0.0.0:8000
Performing system checks...

System check identified no issues (0 silenced).
May 14, 2018 - 09:33:26
Django version 1.11.13, using settings 'Lagerregal.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/template/utils.py", line 65, in __getitem__
    return self._engines[alias]
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/template/backends/django.py", line 126, in get_package_libraries
    module = import_module(entry[1])
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 872, in get_code
  File "<frozen importlib._bootstrap_external>", line 444, in _validate_bytecode_header
ImportError: bad magic number in 'devices.templatetags.rawinclude': b'\x03\xf3\r\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/template/response.py", line 82, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/template/response.py", line 66, in resolve_template
    return get_template(template, using=self.using)
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/template/loader.py", line 18, in get_template
    engines = _engine_list(using)
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/template/loader.py", line 72, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/template/utils.py", line 89, in all
    return [self[alias] for alias in self]
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/template/utils.py", line 89, in <listcomp>
    return [self[alias] for alias in self]
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/template/utils.py", line 80, in __getitem__
    engine = engine_cls(params)
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/template/backends/django.py", line 30, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/template/backends/django.py", line 48, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/template/backends/django.py", line 113, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/template/backends/django.py", line 130, in get_package_libraries
    "trying to load '%s': %s" % (entry[1], e)
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'devices.templatetags.rawinclude': bad magic number in 'devices.templatetags.rawinclude': b'\x03\xf3\r\n'
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/template/utils.py", line 65, in __getitem__
    return self._engines[alias]
KeyError: 'django'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/template/backends/django.py", line 126, in get_package_libraries
    module = import_module(entry[1])
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 872, in get_code
  File "<frozen importlib._bootstrap_external>", line 444, in _validate_bytecode_header
ImportError: bad magic number in 'devices.templatetags.rawinclude': b'\x03\xf3\r\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/core/handlers/base.py", line 131, in get_response
    response = middleware_method(request, response)
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/debug_toolbar/middleware.py", line 134, in process_response
    bits[-2] += toolbar.render_toolbar()
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/debug_toolbar/toolbar.py", line 64, in render_toolbar
    return render_to_string('debug_toolbar/base.html', context)
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/template/loader.py", line 18, in get_template
    engines = _engine_list(using)
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/template/loader.py", line 72, in _engine_list
    return engines.all() if using is None else [engines[using]]
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/template/utils.py", line 89, in all
    return [self[alias] for alias in self]
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/template/utils.py", line 89, in <listcomp>
    return [self[alias] for alias in self]
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/template/utils.py", line 80, in __getitem__
    engine = engine_cls(params)
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/template/backends/django.py", line 30, in __init__
    options['libraries'] = self.get_templatetag_libraries(libraries)
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/template/backends/django.py", line 48, in get_templatetag_libraries
    libraries = get_installed_libraries()
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/template/backends/django.py", line 113, in get_installed_libraries
    for name in get_package_libraries(pkg):
  File "/home/ladmin/.virtualenvs/lagerregal_py3/lib/python3.5/site-packages/django/template/backends/django.py", line 130, in get_package_libraries
    "trying to load '%s': %s" % (entry[1], e)
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'devices.templatetags.rawinclude': bad magic number in 'devices.templatetags.rawinclude': b'\x03\xf3\r\n'
[14/May/2018 09:33:28] "GET /accounts/login/?next=/ HTTP/1.1" 500 135852
```

**Comment by octomike** [comment]
pretty much the same I think

```
[ladmin@lip-dev /opt/Lagerregal (feature-py3)] mkvirtualenv -p $(which python3) py3-test
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/ladmin/.virtualenvs/py3-test/bin/python3
Also creating executable in /home/ladmin/.virtualenvs/py3-test/bin/python
Installing setuptools, pip, wheel...done.
(py3-test) [ladmin@lip-dev /opt/Lagerregal (feature-py3)] rm database.db 
(py3-test) [ladmin@lip-dev /opt/Lagerregal (feature-py3)] pip install -r dependencies.txt >/dev/null
(py3-test) [ladmin@lip-dev /opt/Lagerregal (feature-py3)] cp Lagerregal/template_development.py Lagerregal/settings.py
(py3-test) [ladmin@lip-dev /opt/Lagerregal (feature-py3)] python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, devicegroups, devices, devicetags, devicetypes, locations, mail, main, network, oauth2_provider, reversion, sessions, sites, users
Running migrations:
  Applying contenttypes.0001_initial... OK
[...]
(py3-test) [ladmin@lip-dev /opt/Lagerregal (feature-py3)] python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
May 14, 2018 - 20:34:30
Django version 1.11.13, using settings 'Lagerregal.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[14/May/2018 20:34:39] "GET / HTTP/1.1" 302 0
[14/May/2018 20:34:48] "GET / HTTP/1.1" 302 0
Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "/home/ladmin/.virtualenvs/py3-test/lib/python3.5/site-packages/django/template/utils.py", line 65, in __getitem__
    return self._engines[alias]
KeyError: 'django'

During handling of the above exception, another exception occurred:
```

pip freeze:
```
app-version==1.0.1
certifi==2018.4.16
chardet==3.0.4
Django==1.11.13
django-appconf==1.0.2
django-auth-ldap==1.5.0
django-casper==0.0.4
django-debug-toolbar==1.9.1
django-favicon==0.1.3
django-oauth-toolkit==1.1.2
django-permission==1.0.4
django-reversion==2.0.13
djangorestframework==3.8.2
idna==2.6
model-mommy==1.5.1
oauthlib==2.0.7
Pillow==5.1.0
pyasn1==0.4.2
pyasn1-modules==0.2.1
pystache==0.5.4
python-ldap==3.0.0
pytz==2018.4
requests==2.18.4
six==1.11.0
sqlparse==0.2.4
urllib3==1.22
```

**Comment by octomike** [comment]
huh, got it... `find . -name '*pyc' -delete` helped :)

**Comment by octomike** [comment]
We need to replace `__unicode__` with `__str__` as described here https://docs.djangoproject.com/en/1.11/topics/python3/

Otherwise almost all names are broken :)

```
>>> d = Device.objects.get(id=1315)
>>> d.room.name
'23'
>>> print(d.room)
Room object
```

**Comment by xi** [comment]
Agreed. I would prefer to do that separately though. Leaving the PR open for too long could lead to many merge conflicts.

**Pull request merged**
